### ISSUE TITLE
Tenacity Name

### ISSUE THREAD

**Issue by vchernin** [TheEvilSkeleton/flatpaks#3]
Do you think org.tenacityteam.Tenacity is a better name than com.github.tenacityteam.Tenacity?

A bit of a bikeshed, as who knows by tomorrow Tenacity may no longer be on github for all I know. 

It's also probably worth trying to coordinate with upstream to follow whatever naming style they like, whenever that happens.

**Comment by TheEvilSkeleton** [comment]
Sorry for the late comment, I never received a notification. I tried to change the App ID to `org.tenacityteam.Tenacity`, but apparently that didn't work locally. I want to try to submit a draft MR to the Flathub repo first so I can test whether it builds there or not.

Depends on https://github.com/tenacityteam/tenacity/issues/25.

**Comment by Be-ing** [comment]
> A bit of a bikeshed, as who knows by tomorrow Tenacity may no longer be on github for all I know.

We do want to move off GitHub so I do think this is a good idea to take care of before it is a problem.

**Comment by Semisol** [comment]
We also ~~own~~ are waiting for ownership of tenacityaudio.org so that's nice, but it can be considered owned by us for now.

**Comment by vchernin** [comment]
So maybe `org.tenacityaudio.Tenacity` instead of `org.tenacityteam.Tenacity`?

**Comment by Semisol** [comment]
> So maybe `org.tenacityaudio.Tenacity` instead of `org.tenacityteam.Tenacity`?

Yep.

**Comment by TheEvilSkeleton** [comment]
> > A bit of a bikeshed, as who knows by tomorrow Tenacity may no longer be on github for all I know.
> 
> We do want to move off GitHub so I do think this is a good idea to take care of before it is a problem.

Please, if possible, use an easy-to-use platform like Codeberg because Gitea (Codeberg's base) is a really good alternative to GitHub and really familiar.

**Comment by Semisol** [comment]
> > > A bit of a bikeshed, as who knows by tomorrow Tenacity may no longer be on github for all I know.
> > 
> > 
> > We do want to move off GitHub so I do think this is a good idea to take care of before it is a problem.
> 
> Please, if possible, use an easy-to-use platform like Codeberg because Gitea (Codeberg's base) is a really good alternative to GitHub and really familiar.

We are on https://sr.ht and GH

**Comment by TheEvilSkeleton** [comment]
Any plans in accepting changes in a Gitea instance like Codeberg? I'm asking this because mailing lists and submitting patches via email is not everyone's cup of tea, and I certainly dislike such process. I find MRs and issue trackers convenient and easy to use.

Of course, the more options the better, and having SourceHut is great for those that prefer it, but there are many people that don't like SourceHut because it's unfamiliar for GitHub, GitLab and Gitea users.

**Comment by Be-ing** [comment]
I completely agree, but right now we're just focusing on rebranding and deborking the build system enough to make a release.

**Comment by TheEvilSkeleton** [comment]
Going to close this one because we changed the name.
